version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Shanghai"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
