name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon --stacktrace

    - name: Find JAR file
      id: find_jar
      run: |
        JAR_PATH=$(find build/libs -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" | head -1)
        echo "jar_path=$JAR_PATH" >> $GITHUB_OUTPUT
        echo "jar_name=$(basename $JAR_PATH)" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.find_jar.outputs.jar_path }}
        body: |
          ## Release ${{ github.ref_name }}
          
          This release contains the OnlyTP mod for Minecraft.

          ### Installation
          1. Download the JAR file below
          2. Place it in your Minecraft `mods` folder
          3. Launch Minecraft with Forge installed
          
          ### Changes
          Please see the changelog for details about this version.
        draft: false
        prerelease: false
